### ISSUE TITLE
readinessProbe crashing in long-running cluster

### ISSUE THREAD

**Issue by bbrowning** [3scale/kourier#158]
I've had Kourier deployed in a long-running cluster for about a week now and am seeing the following crash from the readinessProbe using `kourier-gateway:v0.1.2`:

```
  Warning  Unhealthy  2m6s (x36924 over 6d14h)  kubelet, ip-10-0-174-45.us-west-2.compute.internal  (combined from similar events): Readiness probe errored: rpc error: code = Unknown desc = command error: runtime/cgo: pthread_create failed: Resource temporarily unavailable
SIGABRT: abort
PC=0x7f4d3bd468df m=0 sigcode=18446744073709551610

goroutine 0 [idle]:
runtime: unknown pc 0x7f4d3bd468df
stack: frame={sp:0x7ffe147b33a0, fp:0x0} stack=[0x7ffe13fb49e8,0x7ffe147b3a10)
00007ffe147b32a0:  0000000000000000  0000000000000000 
00007ffe147b32b0:  0000000000000000  0000000000000000 
00007ffe147b32c0:  0000000000000000  0000000000000000 
00007ffe147b32d0:  0000000000000000  0000000000000000 
00007ffe147b32e0:  0000000000000000  0000000000000000 
00007ffe147b32f0:  0000000000000000  0000000000000000 
00007ffe147b3300:  0000000000000000  0000000000000000 
00007ffe147b3310:  0000000000000000  00007ffe147b3368 
00007ffe147b3320:  00007ffe147b3378  0000000000000040 
00007ffe147b3330:  0000000000000040  0000000000000001 
00007ffe147b3340:  000000006e43a318  00005647503fcedc 
00007ffe147b3350:  0000000000000000  000056475014ea2e <runtime.callCgoMmap+62> 
00007ffe147b3360:  00007ffe147b3368  0000000000000000 
00007ffe147b3370:  0000000000000000  00007ffe147b33b8 
00007ffe147b3380:  000056475014727a <runtime.mmap.func1+90>  0000000000000000 
00007ffe147b3390:  0000000000210800  0000002200000003 
00007ffe147b33a0: <0000000000000000  00007f4d39afe000 
00007ffe147b33b0:  00007ffe147b33f8  00007ffe147b3430 
00007ffe147b33c0:  00005647500f65d3 <runtime.mmap+179>  00007ffe147b3400 
00007ffe147b33d0:  0000000000000000  0000000000000000 
00007ffe147b33e0:  0000000000000000  0000000000000000 
00007ffe147b33f0:  0000000000000000  00007f4d39afe000 
00007ffe147b3400:  0000564750147220 <runtime.mmap.func1+0>  00007ffe147b3458 
00007ffe147b3410:  00007ffe147b3468  0000000000000040 
00007ffe147b3420:  fffffffe7fffffff  ffffffffffffffff 
00007ffe147b3430:  ffffffffffffffff  ffffffffffffffff 
00007ffe147b3440:  ffffffffffffffff  ffffffffffffffff 
00007ffe147b3450:  ffffffffffffffff  ffffffffffffffff 
00007ffe147b3460:  ffffffffffffffff  ffffffffffffffff 
00007ffe147b3470:  ffffffffffffffff  ffffffffffffffff 
00007ffe147b3480:  ffffffffffffffff  ffffffffffffffff 
00007ffe147b3490:  ffffffffffffffff  ffffffffffffffff 
runtime: unknown pc 0x7f4d3bd468df
stack: frame={sp:0x7ffe147b33a0, fp:0x0} stack=[0x7ffe13fb49e8,0x7ffe147b3a10)
00007ffe147b32a0:  0000000000000000  0000000000000000 
00007ffe147b32b0:  0000000000000000  0000000000000000 
00007ffe147b32c0:  0000000000000000  0000000000000000 
00007ffe147b32d0:  0000000000000000  0000000000000000 
00007ffe147b32e0:  0000000000000000  0000000000000000 
00007ffe147b32f0:  0000000000000000  0000000000000000 
00007ffe147b3300:  0000000000000000  0000000000000000 
00007ffe147b3310:  0000000000000000  00007ffe147b3368 
00007ffe147b3320:  00007ffe147b3378  0000000000000040 
00007ffe147b3330:  0000000000000040  0000000000000001 
00007ffe147b3340:  000000006e43a318  00005647503fcedc 
00007ffe147b3350:  0000000000000000  000056475014ea2e <runtime.callCgoMmap+62> 
00007ffe147b3360:  00007ffe147b3368  0000000000000000 
00007ffe147b3370:  0000000000000000  00007ffe147b33b8 
00007ffe147b3380:  000056475014727a <runtime.mmap.func1+90>  0000000000000000 
00007ffe147b3390:  0000000000210800  0000002200000003 
00007ffe147b33a0: <0000000000000000  00007f4d39afe000 
00007ffe147b33b0:  00007ffe147b33f8  00007ffe147b3430 
00007ffe147b33c0:  00005647500f65d3 <runtime.mmap+179>  00007ffe147b3400 
00007ffe147b33d0:  0000000000000000  0000000000000000 
00007ffe147b33e0:  0000000000000000  0000000000000000 
00007ffe147b33f0:  0000000000000000  00007f4d39afe000 
00007ffe147b3400:  0000564750147220 <runtime.mmap.func1+0>  00007ffe147b3458 
00007ffe147b3410:  00007ffe147b3468  0000000000000040 
00007ffe147b3420:  fffffffe7fffffff  ffffffffffffffff 
00007ffe147b3430:  ffffffffffffffff  ffffffffffffffff 
00007ffe147b3440:  ffffffffffffffff  ffffffffffffffff 
00007ffe147b3450:  ffffffffffffffff  ffffffffffffffff 
00007ffe147b3460:  ffffffffffffffff  ffffffffffffffff 
00007ffe147b3470:  ffffffffffffffff  ffffffffffffffff 
00007ffe147b3480:  ffffffffffffffff  ffffffffffffffff 
00007ffe147b3490:  ffffffffffffffff  ffffffffffffffff 

goroutine 1 [running, locked to thread]:
runtime.systemstack_switch()
  /usr/lib/golang/src/runtime/asm_amd64.s:311 fp=0xc00002c720 sp=0xc00002c718 pc=0x56475014ab70
runtime.newproc(0x564700000000, 0x5647507b5338)
  /usr/lib/golang/src/runtime/proc.go:3243 +0x71 fp=0xc00002c768 sp=0xc00002c720 pc=0x564750129341
runtime.init.6()
  /usr/lib/golang/src/runtime/proc.go:239 +0x37 fp=0xc00002c788 sp=0xc00002c768 pc=0x564750121867
runtime.init()
  <autogenerated>:1 +0x6f fp=0xc00002c798 sp=0xc00002c788 pc=0x56475014a81f
runtime.main()
  /usr/lib/golang/src/runtime/proc.go:147 +0xc2 fp=0xc00002c7e0 sp=0xc00002c798 pc=0x564750121552
runtime.goexit()
  /usr/lib/golang/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc00002c7e8 sp=0xc00002c7e0 pc=0x56475014cc71

goroutine 2 [runnable]:
runtime.forcegchelper()
  /usr/lib/golang/src/runtime/proc.go:242 fp=0xc00002cfe0 sp=0xc00002cfd8 pc=0x564750121880
runtime.goexit()
  /usr/lib/golang/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc00002cfe8 sp=0xc00002cfe0 pc=0x56475014cc71
created by runtime.init.6
  /usr/lib/golang/src/runtime/proc.go:239 +0x37

rax    0x0
rbx    0x6
rcx    0x7f4d3bd468df
rdx    0x0
rdi    0x2
rsi    0x7ffe147b33a0
rbp    0x5647504796ee
rsp    0x7ffe147b33a0
r8     0x0
r9     0x7ffe147b33a0
r10    0x8
r11    0x246
r12    0x5647512de490
r13    0x11
r14    0x56475046c3c4
r15    0x0
rip    0x7f4d3bd468df
rflags 0x246
cs     0x33
fs     0x0
gs     0x0

-----

SIGQUIT: quit
PC=0x56475014e56d m=2 sigcode=0

goroutine 0 [idle]:
runtime.usleep(0x3f59d00002710, 0x0, 0x8000, 0x7f4d39afce20, 0x2710501354fe, 0x3f59d7d62b904, 0x45d964b800, 0x0, 0x0, 0x8, ...)
  /usr/lib/golang/src/runtime/sys_linux_amd64.s:131 +0x3d fp=0x7f4d39afcdc8 sp=0x7f4d39afcda8 pc=0x56475014e56d
runtime.sysmon()
  /usr/lib/golang/src/runtime/proc.go:4282 +0xdd fp=0x7f4d39afce58 sp=0x7f4d39afcdc8 pc=0x56475012bdbd
runtime.mstart1()
  /usr/lib/golang/src/runtime/proc.go:1206 +0xc8 fp=0x7f4d39afce80 sp=0x7f4d39afce58 pc=0x564750124498
runtime.mstart()
  /usr/lib/golang/src/runtime/proc.go:1172 +0x71 fp=0x7f4d39afcea8 sp=0x7f4d39afce80 pc=0x5647501243b1
rax    0xfffffffffffffffc
rbx    0x0
rcx    0x56475014e56d
rdx    0x0
rdi    0x7f4d39afcda8
rsi    0x0
rbp    0x7f4d39afcdb8
rsp    0x7f4d39afcda8
r8     0x0
r9     0x0
r10    0x29458f04e5a7f2
r11    0x202
r12    0x7ffe147b36ae
r13    0x7ffe147b36af
r14    0x7ffe147b37a0
r15    0x7f4d39afcfc0
rip    0x56475014e56d
rflags 0x202
cs     0x33
fs     0x0
gs     0x0

-----

exec failed: container_linux.go:345: starting container process caused "read init-p: connection reset by peer"
, stdout: , stderr: , exit code -1
```

**Comment by jmprusi** [comment]
we should keep this readiness probe but we can replace it by a curl if this is giving us problems.
